<a href="https://colab.research.google.com/github/MegZee/LMR_A-BOW/blob/main/User_behaviour.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [1]:
import json
data = []

for line in open('/content/drive/MyDrive/Dataset_exo/dataset.json', 'r'):
    data.append(json.loads(line))

In [2]:
import pandas as pd
import numpy as np

df = pd.DataFrame(data)
df

                    action     timestamp  step  user
0            copy_exp_code  1.560819e+12     1     1
1            copy_exp_code  1.560819e+12     1     1
2            copy_exp_code  1.560819e+12     1     1
3            copy_exp_code  1.560819e+12     1     1
4            copy_exp_code  1.560820e+12     1     1
...                    ...           ...   ...   ...
78314  tag_remove_by_panel  1.566955e+12     5    58
78315  tag_remove_by_panel  1.566955e+12     5    58
78316  tag_remove_by_panel  1.566955e+12     5    58
78317  tag_remove_by_panel  1.566955e+12     5    58
78318  tag_remove_by_panel  1.566955e+12     5    58

[78319 rows x 4 columns]

In [3]:
noob = [1,4,5,7,10,13,16,19,20,25,27,28,29,30,31,32,33,34,37,39,40,41,43,45,47,49,51,52]
pro = [2,3,6,8,9,11,14,42,46,50,58]
neutral = [12,15,17,18,21,22,23,24,26,35,36,38,44,48,53,54,55,56,57]

In [4]:
len(neutral)

19

In [5]:
df_pro = pd.DataFrame()

for i in pro:
  df_pro = df_pro.append(df[df['user'] == i])

df_pro

                    action     timestamp  step  user
507     click_on_code_by_1  1.557199e+12     1     2
508     click_on_code_by_1  1.557199e+12     1     2
509          copy_exp_code  1.557199e+12     1     2
510          copy_exp_code  1.557199e+12     1     2
511          copy_exp_code  1.557199e+12     1     2
...                    ...           ...   ...   ...
78314  tag_remove_by_panel  1.566955e+12     5    58
78315  tag_remove_by_panel  1.566955e+12     5    58
78316  tag_remove_by_panel  1.566955e+12     5    58
78317  tag_remove_by_panel  1.566955e+12     5    58
78318  tag_remove_by_panel  1.566955e+12     5    58

[19587 rows x 4 columns]

In [6]:
df_noob = pd.DataFrame()

for i in noob:
  df_noob = df_noob.append(df[df['user'] == i])

df_noob

                 action     timestamp  step  user
0         copy_exp_code  1.560819e+12     1     1
1         copy_exp_code  1.560819e+12     1     1
2         copy_exp_code  1.560819e+12     1     1
3         copy_exp_code  1.560819e+12     1     1
4         copy_exp_code  1.560820e+12     1     1
...                 ...           ...   ...   ...
77813  tag_add_by_panel  1.565674e+12     5    52
77814  tag_add_by_panel  1.565674e+12     5    52
77815  tag_add_by_panel  1.565674e+12     5    52
77816  tag_add_by_panel  1.565674e+12     5    52
77817  tag_add_by_panel  1.565674e+12     5    52

[58732 rows x 4 columns]

In [16]:
df_neu = pd.DataFrame()

for i in neutral:
  df_neu = df_neu.append(df[df['user'] == i])

len(df_neu)  #misisng users (the actual number of users is 11+28)

0

# Comparison side by side (avg actions)

In [7]:
dfpro = df_pro['action'].value_counts()//11
dfnoob = df_noob['action'].value_counts()//28 
dfcompare = pd.concat([dfpro, dfnoob], axis=1)
dfcompare.columns = ['Pro', 'Noob']
dfcompare

                           Pro  Noob
scrollbar_M_forward        286   251
leave_middle_aoi           251   375
ipynb_layout_(write_code)  243   240
leave_right_aoi            234   319
scrollbar_M_back           142   147
scrollbar_R_forward        130   141
leave_left_aoi              85   126
ipynb_layout_(add_box)      60    39
scrollbar_R_back            59    70
scrollbar_L_forward         41    53
tab_exp                     33    22
copy_exp_code               32    14
tab_other                   32    20
scrollbar_L_back            25    36
scrollbar_X                 22    30
tag_add_by_panel            20    37
copy_google                 15    10
tag_add_by_click            15    91
click_on_code_by_1          12    18
copy_left                   11    16
left_button_copy             6     8
tab_pra                      3     2
tag_remove_by_panel          3     3
resize_browser               2     0
copy_exp_output              2     4
tag_remove_by_click          2    11
copy_pra_code                0     0
click_on_code_by_3           0     0

# Bounce Rate

In [8]:

count = 0
change = df_noob.iloc[0]['action']

for column in df_noob['action']:
  if column != change:
    count+= 1
    change = column

print(count//11)

221

In [9]:
count = 0
change = df_pro.iloc[0]['action']

for column in df_pro['action']:
  if column != change:
    count = count + 1
    change = column

print(count//11)

90

In [11]:
# predict = []
# count=-2
# for column in df_pro['action']:
#   if column == 'tab_other':
#     if df_pro.iloc[count]['action'] != "tab_other":
#       predict.append(df_pro.iloc[count]['action'])
#   count+=1

# print(predict)

['tab_exp', 'tab_exp', 'tab_exp', 'tab_exp', 'tab_exp', 'tab_exp', 'tab_exp', 'tab_exp', 'scrollbar_X', 'tab_exp', 'tab_exp', 'tab_exp', 'tab_exp', 'tab_exp', 'tab_exp', 'tab_exp', 'tab_exp', 'tab_exp', 'tab_exp', 'tab_exp', 'tab_exp', 'tab_exp', 'tab_exp', 'tab_exp', 'tab_exp', 'tab_exp', 'tab_exp', 'tab_exp', 'tab_exp', 'tab_exp', 'tab_exp', 'tab_exp', 'tab_exp', 'tab_exp', 'tab_exp', 'tab_exp', 'tab_exp', 'tab_exp', 'tab_exp', 'tab_exp', 'tab_exp', 'tab_exp', 'tab_exp', 'tab_exp', 'tab_exp', 'tab_exp', 'tab_exp', 'tab_exp', 'tab_exp', 'tab_exp', 'tab_exp', 'tab_exp', 'tab_exp', 'tab_exp', 'tab_exp', 'tab_exp', 'tab_exp', 'tab_exp', 'tab_exp', 'tab_exp', 'tab_exp', 'tab_exp', 'tab_exp', 'tab_exp', 'tab_exp', 'tab_exp', 'tab_exp', 'tab_exp', 'tab_exp', 'tab_exp', 'tab_exp', 'tab_exp', 'scrollbar_M_forward', 'tab_exp', 'tab_exp', 'tab_exp', 'tab_exp', 'tab_exp', 'tab_exp', 'tab_exp', 'tab_exp', 'tab_exp', 'tab_exp', 'tab_exp', 'tab_exp', 'tab_exp', 'tab_exp', 'tab_exp', 'tab_exp', 'tab_exp', 'scrollbar_M_forward', 'tab_exp', 'tab_exp', 'tab_exp', 'tab_exp', 'tab_exp', 'tab_exp', 'tab_exp', 'tab_exp', 'tab_exp', 'tab_exp', 'tab_exp', 'tab_exp', 'tab_exp', 'tab_exp']

# Actions that trigger external search  
(analyzing the pattern of actions taken before going to **external** search)

In [131]:
# PRO
grouped_pro = df_pro.groupby(['user'])
lBig_pro = list(grouped_pro)
large_pro = []

for i in range(0,10):
  l = []
  l1 = lBig_pro[i][1]

  for i in l1['action']:
    if i not in l:
      l.append(i)
      large_pro.append(i)

print(large_pro)

['click_on_code_by_1', 'copy_exp_code', 'copy_left', 'ipynb_layout_(add_box)', 'ipynb_layout_(write_code)', 'leave_left_aoi', 'leave_middle_aoi', 'leave_right_aoi', 'left_button_copy', 'scrollbar_L_back', 'scrollbar_L_forward', 'scrollbar_M_back', 'scrollbar_M_forward', 'scrollbar_R_back', 'scrollbar_R_forward', 'scrollbar_X', 'tab_exp', 'tab_other', 'tag_add_by_panel', 'copy_google', 'tab_pra', 'tag_add_by_click', 'tag_remove_by_click', 'tag_remove_by_panel', 'copy_exp_output', 'click_on_code_by_1', 'copy_exp_code', 'copy_exp_output', 'copy_google', 'copy_pra_code', 'ipynb_layout_(add_box)', 'ipynb_layout_(write_code)', 'leave_left_aoi', 'leave_middle_aoi', 'leave_right_aoi', 'left_button_copy', 'scrollbar_L_back', 'scrollbar_L_forward', 'scrollbar_M_back', 'scrollbar_M_forward', 'scrollbar_X', 'tab_exp', 'tab_other', 'tag_add_by_panel', 'copy_left', 'scrollbar_R_back', 'scrollbar_R_forward', 'tab_pra', 'tag_remove_by_panel', 'resize_browser', 'click_on_code_by_1', 'copy_exp_code', 'copy_exp_output', 'copy_google', 'copy_left', 'ipynb_layout_(add_box)', 'ipynb_layout_(write_code)', 'leave_left_aoi', 'leave_middle_aoi', 'leave_right_aoi', 'scrollbar_L_back', 'scrollbar_L_forward', 'scrollbar_M_back', 'scrollbar_M_forward', 'scrollbar_R_back', 'scrollbar_R_forward', 'scrollbar_X', 'tab_exp', 'tab_other', 'tab_pra', 'tag_add_by_panel', 'tag_remove_by_panel', 'click_on_code_by_1', 'copy_exp_code', 'copy_left', 'ipynb_layout_(add_box)', 'ipynb_layout_(write_code)', 'leave_left_aoi', 'leave_middle_aoi', 'leave_right_aoi', 'left_button_copy', 'scrollbar_L_back', 'scrollbar_L_forward', 'scrollbar_M_back', 'scrollbar_M_forward', 'scrollbar_R_back', 'scrollbar_R_forward', 'scrollbar_X', 'tab_exp', 'tab_other', 'tab_pra', 'tag_add_by_panel', 'tag_remove_by_panel', 'copy_exp_output', 'copy_google', 'resize_browser', 'tag_add_by_click', 'tag_remove_by_click', 'click_on_code_by_1', 'copy_exp_code', 'copy_exp_output', 'copy_left', 'ipynb_layout_(add_box)', 'ipynb_layout_(write_code)', 'leave_left_aoi', 'leave_middle_aoi', 'leave_right_aoi', 'left_button_copy', 'scrollbar_L_back', 'scrollbar_L_forward', 'scrollbar_M_back', 'scrollbar_M_forward', 'scrollbar_R_back', 'scrollbar_R_forward', 'scrollbar_X', 'tab_exp', 'tab_other', 'copy_google', 'tag_add_by_panel', 'tag_remove_by_panel', 'click_on_code_by_1', 'click_on_code_by_3', 'copy_exp_code', 'copy_google', 'copy_left', 'ipynb_layout_(add_box)', 'ipynb_layout_(write_code)', 'leave_left_aoi', 'leave_middle_aoi', 'leave_right_aoi', 'scrollbar_L_back', 'scrollbar_L_forward', 'scrollbar_M_back', 'scrollbar_M_forward', 'scrollbar_X', 'tab_exp', 'tab_other', 'scrollbar_R_back', 'scrollbar_R_forward', 'tab_pra', 'tag_add_by_click', 'tag_add_by_panel', 'click_on_code_by_1', 'copy_exp_code', 'copy_google', 'copy_left', 'ipynb_layout_(add_box)', 'ipynb_layout_(write_code)', 'leave_left_aoi', 'leave_middle_aoi', 'leave_right_aoi', 'scrollbar_M_back', 'scrollbar_M_forward', 'scrollbar_R_back', 'scrollbar_R_forward', 'scrollbar_X', 'tab_exp', 'tab_other', 'tab_pra', 'scrollbar_L_back', 'scrollbar_L_forward', 'copy_exp_output', 'tag_add_by_panel', 'tag_remove_by_panel', 'click_on_code_by_1', 'click_on_code_by_3', 'copy_left', 'ipynb_layout_(add_box)', 'ipynb_layout_(write_code)', 'leave_left_aoi', 'leave_middle_aoi', 'leave_right_aoi', 'scrollbar_M_back', 'scrollbar_M_forward', 'scrollbar_R_back', 'scrollbar_R_forward', 'tab_exp', 'tab_other', 'tab_pra', 'tag_add_by_click', 'tag_add_by_panel', 'tag_remove_by_click', 'left_button_copy', 'scrollbar_L_back', 'scrollbar_L_forward', 'scrollbar_X', 'copy_google', 'copy_exp_code', 'copy_left', 'ipynb_layout_(add_box)', 'ipynb_layout_(write_code)', 'leave_left_aoi', 'leave_middle_aoi', 'leave_right_aoi', 'left_button_copy', 'scrollbar_L_back', 'scrollbar_L_forward', 'scrollbar_M_back', 'scrollbar_M_forward', 'scrollbar_R_back', 'scrollbar_R_forward', 'scrollbar_X', 'tab_exp', 'tab_other', 'tab_pra', 'tag_add_by_click', 'tag_add_by_panel', 'tag_remove_by_panel', 'click_on_code_by_1', 'copy_exp_output', 'copy_google', 'copy_pra_code', 'resize_browser', 'copy_exp_code', 'copy_google', 'copy_left', 'ipynb_layout_(add_box)', 'ipynb_layout_(write_code)', 'leave_left_aoi', 'leave_middle_aoi', 'leave_right_aoi', 'left_button_copy', 'scrollbar_L_back', 'scrollbar_L_forward', 'scrollbar_M_back', 'scrollbar_M_forward', 'scrollbar_R_back', 'scrollbar_R_forward', 'scrollbar_X', 'tab_exp', 'tab_other', 'tab_pra', 'tag_add_by_panel', 'tag_remove_by_panel', 'click_on_code_by_1', 'tag_add_by_click', 'tag_remove_by_click']

In [12]:
# Noob
grouped_noob = df_noob.groupby(['user'])
lBig_noob = list(grouped_noob)
large_noob = []

print(lBig_noob [0])
# for i in range(0,10):
#   l = []
#   l1 = lBig_noob[i][1]

#   for i in l1['action']:
#     if i not in l:
#       l.append(i)
#       large_noob.append(i)

# print(large_noob)

(1,                     action     timestamp  step  user
0            copy_exp_code  1.560819e+12     1     1
1            copy_exp_code  1.560819e+12     1     1
2            copy_exp_code  1.560819e+12     1     1
3            copy_exp_code  1.560819e+12     1     1
4            copy_exp_code  1.560820e+12     1     1
...                    ...           ...   ...   ...
63177     tag_add_by_panel  1.560826e+12     5     1
63178     tag_add_by_panel  1.560826e+12     5     1
63179     tag_add_by_panel  1.560826e+12     5     1
63180     tag_add_by_panel  1.560826e+12     5     1
63181  tag_remove_by_click  1.560825e+12     5     1

[3678 rows x 4 columns])

In [134]:
pred = []

for i in range(len(large_noob)):
  if large_noob[i] == "tab_other":
    pred.append(large_noob[i-8])
    pred.append(large_noob[i-7])
    pred.append(large_noob[i-6])
    pred.append(large_noob[i-5])
    pred.append(large_noob[i-4])
    pred.append(large_noob[i-3])
    pred.append(large_noob[i-2])
    pred.append(large_noob[i-1])
    pred.append("/n")
    
    
from pprint import pprint
pprint (pred)

['leave_right_aoi',
 'scrollbar_L_back',
 'scrollbar_L_forward',
 'scrollbar_M_back',
 'scrollbar_M_forward',
 'scrollbar_R_back',
 'scrollbar_R_forward',
 'tab_exp',
 '/n',
 'leave_left_aoi',
 'leave_middle_aoi',
 'leave_right_aoi',
 'scrollbar_L_back',
 'scrollbar_L_forward',
 'scrollbar_M_back',
 'scrollbar_M_forward',
 'tab_exp',
 '/n',
 'scrollbar_L_back',
 'scrollbar_L_forward',
 'scrollbar_M_back',
 'scrollbar_M_forward',
 'scrollbar_R_back',
 'scrollbar_R_forward',
 'scrollbar_X',
 'tab_exp',
 '/n',
 'leave_middle_aoi',
 'leave_right_aoi',
 'scrollbar_L_back',
 'scrollbar_L_forward',
 'scrollbar_M_back',
 'scrollbar_M_forward',
 'scrollbar_R_forward',
 'tab_exp',
 '/n',
 'scrollbar_L_back',
 'scrollbar_L_forward',
 'scrollbar_M_back',
 'scrollbar_M_forward',
 'scrollbar_R_back',
 'scrollbar_R_forward',
 'scrollbar_X',
 'tab_exp',
 '/n',
 'scrollbar_L_back',
 'scrollbar_L_forward',
 'scrollbar_M_back',
 'scrollbar_M_forward',
 'scrollbar_R_back',
 'scrollbar_R_forward',
 'scrollbar_X',
 'tab_exp',
 '/n',
 'scrollbar_L_forward',
 'scrollbar_M_back',
 'scrollbar_M_forward',
 'scrollbar_R_back',
 'tab_exp',
 'tab_pra',
 'copy_exp_output',
 'scrollbar_R_forward',
 '/n',
 'scrollbar_L_back',
 'scrollbar_L_forward',
 'scrollbar_M_back',
 'scrollbar_M_forward',
 'scrollbar_R_back',
 'scrollbar_R_forward',
 'scrollbar_X',
 'tab_exp',
 '/n',
 'scrollbar_L_back',
 'scrollbar_L_forward',
 'scrollbar_M_back',
 'scrollbar_M_forward',
 'scrollbar_R_back',
 'scrollbar_R_forward',
 'scrollbar_X',
 'tab_exp',
 '/n',
 'scrollbar_L_back',
 'scrollbar_L_forward',
 'scrollbar_M_back',
 'scrollbar_M_forward',
 'scrollbar_R_back',
 'scrollbar_R_forward',
 'scrollbar_X',
 'tab_exp',
 '/n']

In [135]:
for i in range(len(large_pro)):
  if large_pro[i] == "tab_other":
    pred.append(large_pro[i-7])
    pred.append(large_pro[i-6])
    pred.append(large_pro[i-5])
    pred.append(large_pro[i-4])
    pred.append(large_pro[i-3])
    pred.append(large_pro[i-2])
    pred.append(large_pro[i-1])
    
    pred.append("/n")
    
    
from pprint import pprint
pprint (pred)

['leave_right_aoi',
 'scrollbar_L_back',
 'scrollbar_L_forward',
 'scrollbar_M_back',
 'scrollbar_M_forward',
 'scrollbar_R_back',
 'scrollbar_R_forward',
 'tab_exp',
 '/n',
 'leave_left_aoi',
 'leave_middle_aoi',
 'leave_right_aoi',
 'scrollbar_L_back',
 'scrollbar_L_forward',
 'scrollbar_M_back',
 'scrollbar_M_forward',
 'tab_exp',
 '/n',
 'scrollbar_L_back',
 'scrollbar_L_forward',
 'scrollbar_M_back',
 'scrollbar_M_forward',
 'scrollbar_R_back',
 'scrollbar_R_forward',
 'scrollbar_X',
 'tab_exp',
 '/n',
 'leave_middle_aoi',
 'leave_right_aoi',
 'scrollbar_L_back',
 'scrollbar_L_forward',
 'scrollbar_M_back',
 'scrollbar_M_forward',
 'scrollbar_R_forward',
 'tab_exp',
 '/n',
 'scrollbar_L_back',
 'scrollbar_L_forward',
 'scrollbar_M_back',
 'scrollbar_M_forward',
 'scrollbar_R_back',
 'scrollbar_R_forward',
 'scrollbar_X',
 'tab_exp',
 '/n',
 'scrollbar_L_back',
 'scrollbar_L_forward',
 'scrollbar_M_back',
 'scrollbar_M_forward',
 'scrollbar_R_back',
 'scrollbar_R_forward',
 'scrollbar_X',
 'tab_exp',
 '/n',
 'scrollbar_L_forward',
 'scrollbar_M_back',
 'scrollbar_M_forward',
 'scrollbar_R_back',
 'tab_exp',
 'tab_pra',
 'copy_exp_output',
 'scrollbar_R_forward',
 '/n',
 'scrollbar_L_back',
 'scrollbar_L_forward',
 'scrollbar_M_back',
 'scrollbar_M_forward',
 'scrollbar_R_back',
 'scrollbar_R_forward',
 'scrollbar_X',
 'tab_exp',
 '/n',
 'scrollbar_L_back',
 'scrollbar_L_forward',
 'scrollbar_M_back',
 'scrollbar_M_forward',
 'scrollbar_R_back',
 'scrollbar_R_forward',
 'scrollbar_X',
 'tab_exp',
 '/n',
 'scrollbar_L_back',
 'scrollbar_L_forward',
 'scrollbar_M_back',
 'scrollbar_M_forward',
 'scrollbar_R_back',
 'scrollbar_R_forward',
 'scrollbar_X',
 'tab_exp',
 '/n',
 'scrollbar_L_forward',
 'scrollbar_M_back',
 'scrollbar_M_forward',
 'scrollbar_R_back',
 'scrollbar_R_forward',
 'scrollbar_X',
 'tab_exp',
 '/n',
 'left_button_copy',
 'scrollbar_L_back',
 'scrollbar_L_forward',
 'scrollbar_M_back',
 'scrollbar_M_forward',
 'scrollbar_X',
 'tab_exp',
 '/n',
 'scrollbar_L_forward',
 'scrollbar_M_back',
 'scrollbar_M_forward',
 'scrollbar_R_back',
 'scrollbar_R_forward',
 'scrollbar_X',
 'tab_exp',
 '/n',
 'scrollbar_L_forward',
 'scrollbar_M_back',
 'scrollbar_M_forward',
 'scrollbar_R_back',
 'scrollbar_R_forward',
 'scrollbar_X',
 'tab_exp',
 '/n',
 'scrollbar_L_forward',
 'scrollbar_M_back',
 'scrollbar_M_forward',
 'scrollbar_R_back',
 'scrollbar_R_forward',
 'scrollbar_X',
 'tab_exp',
 '/n',
 'leave_right_aoi',
 'scrollbar_L_back',
 'scrollbar_L_forward',
 'scrollbar_M_back',
 'scrollbar_M_forward',
 'scrollbar_X',
 'tab_exp',
 '/n',
 'leave_right_aoi',
 'scrollbar_M_back',
 'scrollbar_M_forward',
 'scrollbar_R_back',
 'scrollbar_R_forward',
 'scrollbar_X',
 'tab_exp',
 '/n',
 'leave_middle_aoi',
 'leave_right_aoi',
 'scrollbar_M_back',
 'scrollbar_M_forward',
 'scrollbar_R_back',
 'scrollbar_R_forward',
 'tab_exp',
 '/n',
 'scrollbar_L_forward',
 'scrollbar_M_back',
 'scrollbar_M_forward',
 'scrollbar_R_back',
 'scrollbar_R_forward',
 'scrollbar_X',
 'tab_exp',
 '/n',
 'scrollbar_L_forward',
 'scrollbar_M_back',
 'scrollbar_M_forward',
 'scrollbar_R_back',
 'scrollbar_R_forward',
 'scrollbar_X',
 'tab_exp',
 '/n']

# Attempting to calculate time

In [120]:
noob_stamps = []
for index, i in lBig_noob:
  noob_stamps.append(i['timestamp'])

list_duration_noob = []

for i in noob_stamps:
  df_temp = pd.DataFrame(i)
  calc = df_temp.iloc[len(df_temp)-1] - df_temp.iloc[0]
  list_duration_noob.append(calc.mean()/60000)

print(list_duration_noob)
print(len(list_duration_noob))
avg_noob = sum(list_duration_noob)/len(list_duration_noob)
print(avg_noob//1)

[86.01201666666667, 50.003766666666664, 63.45215, 40.95175, 39.99681666666667, 51.127766666666666, 52.314616666666666, 61.13296666666667, 52.87818333333333, 50.42325, 62.500233333333334, 40.60115, 35.163916666666665, 71.70026666666666, 45.28633333333333, 49.08545, 58.739066666666666, 48.672916666666666, 73.8094, 47.24668333333333, 43.45583333333333, 61.43221666666667, 51.68893333333333, 76.37891666666667, 69.08615, 78.16156666666667, 48.732416666666666, 76.73636666666667]
28
56.0

In [121]:
pro_stamps = []
for index, i in lBig_pro:
  pro_stamps.append(i['timestamp'])

list_duration_pro = []

for i in pro_stamps:
  df_temp = pd.DataFrame(i)
  calc = df_temp.iloc[len(df_temp)-1] - df_temp.iloc[0]
  list_duration_pro.append(calc.mean()/60000)

print(list_duration_pro)
print(len(list_duration_pro))
avg_pro = sum(list_duration_pro)/len(list_duration_pro)
print(avg_pro//1)

[39.02558333333333, 62.29078333333333, 47.03093333333333, 58.965833333333336, 55.96061666666667, 83.4515, 63.623083333333334, 51.2803, 60.43025, 36.47088333333333, 43.9827]
11
54.0